// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _365MigrationTracker.Data;

#nullable disable

namespace _365MigrationTracker.Data.Migrations
{
    [DbContext(typeof(DashboardDbContext))]
    [Migration("20260903082148_AddTotalCountsToMetricsSnapshot")]
    partial class AddTotalCountsToMetricsSnapshot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("_365MigrationTracker.Data.MetricSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CapturedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("CollectionDurationMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CollectionSucceeded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EntraJoinedDevices")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("HybridDevices")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PendingHybridDevices")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SyncedGroups")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SyncedUsers")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalDevices")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalGroups")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalUsers")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CapturedAtUtc")
                        .HasDatabaseName("IX_MetricSnapshot_CapturedAtUtc");

                    b.HasIndex("CollectionSucceeded")
                        .HasDatabaseName("IX_MetricSnapshot_CollectionSucceeded");

                    b.ToTable("MetricSnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
